.de EX
.nf
.ft CW
..
.de EE
.br
.fi
.ft 1
..
.TH FF 1
.CT 1 files prog_other
.SH NAME
ff \- fuzzy-find: fuzzy completion for finding files
.SH SYNOPSIS
.B ff
[
.BI \-dDhilRt
]
[
.BI \-c
.I char
]
[
.BI \-n
.I count
]
[
.BI \-r
.I root
]
.I pattern
.SH DESCRIPTION
.I ff
searches a directory tree with basic
.I fuzzy-completion.
I wrote it because
.I `find -name "blah"`
only scans filenames (not their parent directories), and
regular expressions for fuzzy completion are cumbersome.

Searching for
.I "aeiou"
will print any paths that match the re
.I ".*a.*e.*i.*o.*u.*"

By default,
.I ff
searches recursively from the current directory, but its
search root can be set with the
.I `-r`
option.

.I `ff`
query query strings are not regular expressions - characters such as
.I '.'
and
.I '-'
match literally. Any sections enclosed in
.I '/'s
will be required to match within the same path element, and the
consecutive match character (default
.I '='
) toggles exact matching.
(The default is
.I '='
because it doesn't mean anything in basic REs and it's
usually unshifted on keyboards.)

.SH OPTIONS
.TP
.BI \-c " CHAR"
char to toggle
.I Consecutive
match (default:
.I '='
)
.TP
.BI \-d
show
.I Dotfiles
.TP
.BI \-D
only show
.I Directories
.TP
.BI \-h
show this
.I Help
.TP
.BI \-i
.I case-Insensitive
search
.TP
.BI \-l
follow
.I Links
(warning: no cycle detection)
.TP
.BI \-r " ROOT"
set search
.I Root
(default: .)
.TP
.BI \-R
don't recurse subdirectories
.TP
.BI \-t
run
.I Tests
and exit

.SH EXAMPLES

.I `ff aeiou`
matches both
.I `~/and/the/first/one/used.txt`
and
.I `~/after_the_furious_ultimatum.txt`,
because the characters 'a', 'e', 'i', 'o', and 'u' appear sequentially.

.I `ff a/e/i/o/u`
only matches
.I `~/and/the/first/one/used.txt`,
since the
.I `/`s
require each vowel to appear in distinct directory elements.

.I `ff ae=iou=`
would only match
.I `~/after_the_furious_ultimatum.txt`,
since it matches an 'a', then an 'e', then the `=`s specify a 
.B consecutive
"iou" string. (The second '=' toggles off the consecutive match,
but is optional since it is at the end of the pattern.)

.SH SEE ALSO
.IR find (1)
.SH BUGS
Not a web framework.
